# This workflow just updates the readme file with the most latest file i changed if it hasn't already been done.

name: ReadMe updater

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Updating
      run: |
        python latest
