# This workflow just updates the readme file with the most latest file i changed if it hasn't already been done.

name: ReadMe updater

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Updating
      run: |
        python latest

    - name: Sending back files
      uses: EndBug/add-and-commit@v7.5.0
      with:
        message: "Updated readme"
        author_name: "github"